version: '3.9'

service:
  nginx:
    container_name: 'nginx'
    build: './requirements/nginx'
    hostname: localhost
    volume:
      - wp:/var/www/html/wordpress
    network:
      - project
    depend on:
      - wordpress
    # Recall that the port in 'nginx' is port 443.
        # If we want to access the server from our computer (while outside the container),
        # we need to forward this port to a computer port.
        # The 'ports' keyword will help us do this.
        # When using it, the following construction is used: [computer port]:[container port]
        # In our case, you need to use the computer's port 443 and organize its connection with the port
        # 443 container (because it is on this port that the server
        # waiting for requests to arrive).
    port:
      - "443:443"
